### ISSUE TITLE
how to use？

### ISSUE THREAD

**Issue by ghost** [tamatebako/tebako-tools#4]
How to use these scripts, use homebrew to install arm64 library on intel mac, for example: use fdk-aac to make a detailed operation instruction

**Comment by maxirmx** [comment]
@ghost, thank you gor your question

> How to use these scripts, use homebrew to install arm64 library on intel mac, for example: use fdk-aac to make a detailed operation instruction

There is a dicussion re how to cross install on mac
https://stackoverflow.com/questions/70821136/can-i-install-arm64-libraries-on-x86-64-with-homebrew/70822921#70822921
https://github.com/orgs/Homebrew/discussions/2843

If you can convert it to detailed instruction your help will be much appreciated
